services: 
  db:
    image: postgres
    restart: unless-stopped 
    environment:
      POSTGRES_HOST: ${DATABASE_HOST}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}  
    volumes:
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:      